common/common.h: Introduce (more) hygenic definitions of SWAP, min and max macros.
These contained declarations of variables which shadowed other
variable declarations in the main code, leading to warnings like those
shown below.  I also modified the macros to use parens around all
expanded parameters, and added a comment explaining why the values are
copied to local variables.

In file included from ../common/string-utils.h:26:0,
                 from extract.c:46:
../common/common.h:29:31: error: declaration of ‘c’ shadows a previous local [-Werror=shadow]
 #define max(a,b) ({ typeof(a) c = a; typeof(b) d = b; MAX(c,d); })
                               ^
extract.c:250:40: note: in expansion of macro ‘max’
      if (abs(bitmap.width) > INT32_MAX/max(4, bitmap.bit_count)) {
                                        ^~~
extract.c:103:11: note: shadowed declaration is here
  uint32_t c, d;
           ^
In file included from ../common/string-utils.h:26:0,
                 from extract.c:46:
../common/common.h:29:48: error: declaration of ‘d’ shadows a previous local [-Werror=shadow]
 #define max(a,b) ({ typeof(a) c = a; typeof(b) d = b; MAX(c,d); })
                                                ^
extract.c:250:40: note: in expansion of macro ‘max’
      if (abs(bitmap.width) > INT32_MAX/max(4, bitmap.bit_count)) {
                                        ^~~
extract.c:103:14: note: shadowed declaration is here
  uint32_t c, d;
              ^

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>
Thanks: Dan Berrange