common/llist.c: Avoid unnecessary comparisons unsigned < 0.
Unsigned is always zero or positive, so there is no need to compare
with < 0.

The original warnings/errors from GCC were:

llist.c: In function ‘llist_get’:
llist.c:284:12: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
  if (index < 0 || index >= list->size)
            ^
llist.c: In function ‘llist_set’:
llist.c:297:12: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
  if (index < 0 || index >= list->size)
            ^
llist.c: In function ‘llist_add_at’:
llist.c:319:12: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
  if (index < 0 || index > list->size)
            ^
llist.c: In function ‘llist_remove_at’:
llist.c:346:12: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
  if (index < 0 || index >= list->size)
            ^

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>